"""BitChat binary packet protocol package."""

from bitchat.protocol.constants import (
    BITCHAT_CHARACTERISTIC_UUID,
    BITCHAT_SERVICE_UUID,
    BLOCK_SIZES,
    BROADCAST_RECIPIENT,
    COVER_TRAFFIC_PREFIX,
    CURRENT_PROTOCOL_VERSION,
    FIXED_HEADER_SIZE,
    FLAG_HAS_RECIPIENT,
    FLAG_HAS_SIGNATURE,
    FLAG_IS_COMPRESSED,
    FRAGMENT_CHUNK_SIZE,
    FRAGMENT_HEADER_SIZE,
    FRAGMENT_ID_SIZE,
    FRAGMENTATION_THRESHOLD,
    MAX_ACTIVE_ASSEMBLIES,
    MAX_FRAGMENTS_PER_ASSEMBLY,
    MAX_PADDING_SIZE,
    MAX_REASSEMBLED_BYTES,
    MAXIMUM_PROTOCOL_VERSION,
    MINIMUM_PACKET_SIZE,
    MINIMUM_PROTOCOL_VERSION,
    PADDING_OVERHEAD_ESTIMATE,
    RECIPIENT_ID_SIZE,
    SENDER_ID_SIZE,
    SIGNATURE_SIZE,
    MessageType,
)
from bitchat.protocol.decoder import decode_packet, unpad_packet_data
from bitchat.protocol.encoder import (
    encode_packet,
    get_optimal_block_size,
    pad_packet_data,
)
from bitchat.protocol.fragmentation import (
    create_fragment_payload,
    encode_fragment_packets,
    fragment_encoded_packet,
    fragment_packet,
    generate_fragment_id,
    parse_fragment_payload,
    should_fragment,
    split_chunks,
)
from bitchat.protocol.packet import BitchatPacket, peer_id_from_hex, peer_id_to_hex
from bitchat.protocol.reassembly import FragmentReassembler

__all__ = [
    "BITCHAT_CHARACTERISTIC_UUID",
    "BITCHAT_SERVICE_UUID",
    "BLOCK_SIZES",
    "BROADCAST_RECIPIENT",
    "COVER_TRAFFIC_PREFIX",
    "CURRENT_PROTOCOL_VERSION",
    "FIXED_HEADER_SIZE",
    "FLAG_HAS_RECIPIENT",
    "FLAG_HAS_SIGNATURE",
    "FLAG_IS_COMPRESSED",
    "FRAGMENTATION_THRESHOLD",
    "FRAGMENT_CHUNK_SIZE",
    "FRAGMENT_HEADER_SIZE",
    "FRAGMENT_ID_SIZE",
    "MAXIMUM_PROTOCOL_VERSION",
    "MAX_ACTIVE_ASSEMBLIES",
    "MAX_FRAGMENTS_PER_ASSEMBLY",
    "MAX_PADDING_SIZE",
    "MAX_REASSEMBLED_BYTES",
    "MINIMUM_PACKET_SIZE",
    "MINIMUM_PROTOCOL_VERSION",
    "PADDING_OVERHEAD_ESTIMATE",
    "RECIPIENT_ID_SIZE",
    "SENDER_ID_SIZE",
    "SIGNATURE_SIZE",
    "BitchatPacket",
    "FragmentReassembler",
    "MessageType",
    "create_fragment_payload",
    "decode_packet",
    "encode_fragment_packets",
    "encode_packet",
    "fragment_encoded_packet",
    "fragment_packet",
    "generate_fragment_id",
    "get_optimal_block_size",
    "pad_packet_data",
    "parse_fragment_payload",
    "peer_id_from_hex",
    "peer_id_to_hex",
    "should_fragment",
    "split_chunks",
    "unpad_packet_data",
]
