"""BitChat binary packet protocol package."""

from bitchat.protocol.constants import (
    BITCHAT_CHARACTERISTIC_UUID,
    BITCHAT_SERVICE_UUID,
    BLOCK_SIZES,
    BROADCAST_RECIPIENT,
    COVER_TRAFFIC_PREFIX,
    CURRENT_PROTOCOL_VERSION,
    FIXED_HEADER_SIZE,
    FLAG_HAS_RECIPIENT,
    FLAG_HAS_SIGNATURE,
    FLAG_IS_COMPRESSED,
    MAX_PADDING_SIZE,
    MAXIMUM_PROTOCOL_VERSION,
    MINIMUM_PACKET_SIZE,
    MINIMUM_PROTOCOL_VERSION,
    PADDING_OVERHEAD_ESTIMATE,
    RECIPIENT_ID_SIZE,
    SENDER_ID_SIZE,
    SIGNATURE_SIZE,
    MessageType,
)
from bitchat.protocol.decoder import decode_packet, unpad_packet_data
from bitchat.protocol.encoder import (
    encode_packet,
    get_optimal_block_size,
    pad_packet_data,
)
from bitchat.protocol.packet import BitchatPacket, peer_id_from_hex, peer_id_to_hex

__all__ = [
    "BITCHAT_CHARACTERISTIC_UUID",
    "BITCHAT_SERVICE_UUID",
    "BLOCK_SIZES",
    "BROADCAST_RECIPIENT",
    "COVER_TRAFFIC_PREFIX",
    "CURRENT_PROTOCOL_VERSION",
    "FIXED_HEADER_SIZE",
    "FLAG_HAS_RECIPIENT",
    "FLAG_HAS_SIGNATURE",
    "FLAG_IS_COMPRESSED",
    "MAXIMUM_PROTOCOL_VERSION",
    "MAX_PADDING_SIZE",
    "MINIMUM_PACKET_SIZE",
    "MINIMUM_PROTOCOL_VERSION",
    "PADDING_OVERHEAD_ESTIMATE",
    "RECIPIENT_ID_SIZE",
    "SENDER_ID_SIZE",
    "SIGNATURE_SIZE",
    "BitchatPacket",
    "MessageType",
    "decode_packet",
    "encode_packet",
    "get_optimal_block_size",
    "pad_packet_data",
    "peer_id_from_hex",
    "peer_id_to_hex",
    "unpad_packet_data",
]
